# Generated by Django 6.0.7 on 2026-09-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(upload_to='bags')),
                ('photo_back', models.ImageField(upload_to='bags')),
                ('detail_bags', models.TextField(default=None)),
            ],
        ),
    ]
