<<<<<<< Updated upstream
# Generated by Django 6.1.1 on 2026-09-08 13:42
=======
# Generated by Django 6.0.7 on 2026-09-08 15:07
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< Updated upstream
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('front_photo', models.ImageField(default=None, upload_to='itemphoto/')),
                ('back_photo', models.ImageField(default=None, upload_to='itemphoto/')),
                ('like', models.IntegerField()),
                ('detail', models.TextField(default=None)),
=======
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(default=None, upload_to='photo/')),
                ('detail', models.TextField(default=None)),
                ('star', models.ImageField(default=None, upload_to='photo/')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
>>>>>>> Stashed changes
            ],
        ),
    ]
