# Generated by Django 6.1 on 2026-09-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='like',
        ),
    ]
