# Generated by Django 6.1 on 2026-09-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hat',
            name='names',
        ),
        migrations.AddField(
            model_name='hat',
            name='Team',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hat',
            name='quality',
            field=models.ImageField(default='', upload_to='hats'),
            preserve_default=False,
        ),
    ]
