# Generated by Django 6.0.7 on 2026-09-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bags',
            name='photo_back',
        ),
    ]
