# Generated by Django 6.1 on 2026-09-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_remove_hat_names_hat_team_hat_quality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hat',
            old_name='Team',
            new_name='names',
        ),
        migrations.RemoveField(
            model_name='hat',
            name='quality',
        ),
        migrations.AlterField(
            model_name='hat',
            name='photo',
            field=models.ImageField(upload_to='hat'),
        ),
    ]
