# Generated by Django 6.0.7 on 2026-09-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_remove_bags_photo_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='bags',
            name='photos',
            field=models.ImageField(default='', upload_to='bags'),
            preserve_default=False,
        ),
    ]
