# Generated by Django 6.0.7 on 2026-09-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_bags_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('photo', models.ImageField(default=None, upload_to='slide_show/')),
                ('photos', models.ImageField(default=None, upload_to='slide_show/')),
                ('orders', models.IntegerField()),
            ],
        ),
    ]
