# Generated by Django 6.1 on 2026-09-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_rename_team_hat_names_remove_hat_quality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='more',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('photo', models.ImageField(default=None, upload_to='slide_show/')),
                ('orders', models.IntegerField()),
            ],
        ),
    ]
