# Generated by Django 6.0.7 on 2026-09-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='photos',
        ),
        migrations.AlterField(
            model_name='slide',
            name='photo',
            field=models.ImageField(default=None, upload_to='sl_bags/'),
        ),
    ]
