# Generated by Django 6.0.7 on 2026-09-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_remove_slide_photos_alter_slide_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.AddField(
            model_name='bags',
            name='photoback',
            field=models.ImageField(default='', upload_to='bags'),
            preserve_default=False,
        ),
    ]
