# Generated by Django 6.0.7 on 2026-09-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_delete_slide_bags_photoback'),
    ]

    operations = [
        migrations.AddField(
            model_name='bags',
            name='name_model',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
